import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/components/ThemeProvider";
import QClientProvider from "@/components/clientProvider";
import { cookies } from "next/headers";
import Script from "next/script";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const fetchAuthUser = async () => {
  const response = await fetch(`${process.env.NEXT_PUBLIC_API_URL}/auth/me`, {
    method: "POST",
    cache: "no-store",
  });
  if (response.status !== 200) {
    throw new Error("Failed to fetch user");
  }
  const data = await response.json();
  return data.user;
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let user;
  const cookieStore = await cookies();
  const cookie = cookieStore.get("refresh_token");
  try {
    if (cookie) {
      user = await fetchAuthUser();
    }
  } catch (err) {
    console.error("Failed to fetch user:", err);
  }

  return (
    <html lang="en">
      <head>
        <Script
          id="ms-clarity"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
            (function(c,l,a,r,i,t,y){
                c[a]=c[a]||function(){(c[a].q=c[a].q||[]).push(arguments)};
                t=l.createElement(r);t.async=1;t.src="https://www.clarity.ms/tag/" + i;
                y=l.getElementsByTagName(r)[0];y.parentNode.insertBefore(t,y);
            })(window, document, "clarity", "script", "sxq10186wt");
          `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <QClientProvider user={user}>
          <ThemeProvider>{children}</ThemeProvider>
        </QClientProvider>
      </body>
    </html>
  );
}
